### ISSUE TITLE
Install the Zsh

### ISSUE THREAD

**Issue by dminca** [WizDevOps/containerschiff#7]
Instead of using good ol` bash, just install zsh, [here's an example](https://github.com/heybigname/ansible/blob/master/tasks/ohmyzsh.yml)

``` yml

---
# oh-my-zsh

- name: oh-my-zsh | Install oh-my-zsh
  apt: name={{ item }}  state=latest update_cache=yes
  with_items:
   - git
   - zsh
   - git-core

- name: oh-my-zsh | Clone down repository
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/vagrant/.oh-my-zsh

- name: oh-my-zsh | Remove standard .zshrc
  file: path=/home/vagrant/.zshrc state=absent

- name: oh-my-zsh | Deploy new .zshrc
  template: src=files/zshrc.in dest=/home/vagrant/.zshrc owner=vagrant

- name: oh-my-zsh | Set zsh as default shell
  user: name=vagrant shell=/bin/zsh
```

[another example](https://github.com/RaymiiOrg/ansible/tree/master/oh-my-zsh) on how to install **zsh**

``` yml

---
## Install Oh-my-zsh

- hosts: spcs
  user: remy
  sudo: True
  connection: ssh # or paramiko

  vars:
    user: remy
    pbname: $inventory_hostname
    distro: ${ansible_distribution}
    pkg_mgr: ${ansible_pkg_mgr}
    zsh_theme: steeef

  tasks:
  - name: Install git and zsh 
    apt: name=$item state=latest update_cache=yes
    with_items:
     - git
     - zsh
     - git-core

  - name: Clone oh-my-zsh repo
    git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/$user/.oh-my-zsh

  - name: deploy .zshrc
    template: src=files/zshrc.in dest=/home/$user/conf/zshrc owner=$user

  - name: remove standard zshrc
    file: path=/home/$user/.zshrc state=absent

  - name: Create conf folder in home directory
    file: path=/home/$user/conf/ state=directory owner=$user

  - name: symlink zshrc
    file: path=/home/$user/.zshrc src=/home/$user/conf/zshrc state=link owner=$user

  - name: Set zsh as default shell
    user: name=$user shell=/bin/zsh
```
