### ISSUE TITLE
Merge all roles together in the master branch

### ISSUE THREAD

**Issue by dminca** [WizDevOps/containerschiff#85]
Use the wonderful Ansible fact `{{ ansible_os_family }}` and let it decide when running the playbook which task files to load.

Merge all tasks under their designated role directory, then load them accordingly:

```yml
# roles/docker/tasks/main.yml
- import_tasks: "{{ ansible_os_family }}.yml"

# roles/docker/tasks/RedHat.yml
- include_tasks: engine.yml
```

Understanding the difference between Ansible's facts `ansible_os_family` and `ansible_distribution`:

```yml
ansible_os_family:       
  RedHat                 
    ansible_distribution:
      - Fedora           
  Debian                 
    ansible_distribution:
      - Ubuntu           
      - Debian           
  Archlinux              
    ansible_distribution:
      - Archlinux        
```

##### Useful resources
- [list of values for `ansible_os_family`][1]

[1]: https://github.com/abaez/ansible-role-docker/tree/master/tasks/os_family
